/* Font Face Observer v2.0.13 - © Bram Stein. License: BSD-3-Clause */(function(){'use strict';var f,g=[];function l(a){g.push(a);1==g.length&&f()}function m(){for(;g.length;)g[0](),g.shift()}f=function(){setTimeout(m)};function n(a){this.a=p;this.b=void 0;this.f=[];var b=this;try{a(function(a){q(b,a)},function(a){r(b,a)})}catch(c){r(b,c)}}var p=2;function t(a){return new n(function(b,c){c(a)})}function u(a){return new n(function(b){b(a)})}function q(a,b){if(a.a==p){if(b==a)throw new TypeError;var c=!1;try{var d=b&&b.then;if(null!=b&&"object"==typeof b&&"function"==typeof d){d.call(b,function(b){c||q(a,b);c=!0},function(b){c||r(a,b);c=!0});return}}catch(e){c||r(a,e);return}a.a=0;a.b=b;v(a)}}
function r(a,b){if(a.a==p){if(b==a)throw new TypeError;a.a=1;a.b=b;v(a)}}function v(a){l(function(){if(a.a!=p)for(;a.f.length;){var b=a.f.shift(),c=b[0],d=b[1],e=b[2],b=b[3];try{0==a.a?"function"==typeof c?e(c.call(void 0,a.b)):e(a.b):1==a.a&&("function"==typeof d?e(d.call(void 0,a.b)):b(a.b))}catch(h){b(h)}}})}n.prototype.g=function(a){return this.c(void 0,a)};n.prototype.c=function(a,b){var c=this;return new n(function(d,e){c.f.push([a,b,d,e]);v(c)})};
function w(a){return new n(function(b,c){function d(c){return function(d){h[c]=d;e+=1;e==a.length&&b(h)}}var e=0,h=[];0==a.length&&b(h);for(var k=0;k<a.length;k+=1)u(a[k]).c(d(k),c)})}function x(a){return new n(function(b,c){for(var d=0;d<a.length;d+=1)u(a[d]).c(b,c)})};window.Promise||(window.Promise=n,window.Promise.resolve=u,window.Promise.reject=t,window.Promise.race=x,window.Promise.all=w,window.Promise.prototype.then=n.prototype.c,window.Promise.prototype["catch"]=n.prototype.g);}());

(function(){function k(a,b){document.addEventListener?a.addEventListener("scroll",b,!1):a.attachEvent("scroll",b)}function m(a){document.body?a():document.addEventListener?document.addEventListener("DOMContentLoaded",function c(){document.removeEventListener("DOMContentLoaded",c);a()}):document.attachEvent("onreadystatechange",function l(){if("interactive"==document.readyState||"complete"==document.readyState)document.detachEvent("onreadystatechange",l),a()})};function r(a){this.a=document.createElement("div");this.a.setAttribute("aria-hidden","true");this.a.appendChild(document.createTextNode(a));this.b=document.createElement("span");this.c=document.createElement("span");this.h=document.createElement("span");this.f=document.createElement("span");this.g=-1;this.b.style.cssText="max-width:none;display:inline-block;position:absolute;height:100%;width:100%;overflow:scroll;font-size:16px;";this.c.style.cssText="max-width:none;display:inline-block;position:absolute;height:100%;width:100%;overflow:scroll;font-size:16px;";
this.f.style.cssText="max-width:none;display:inline-block;position:absolute;height:100%;width:100%;overflow:scroll;font-size:16px;";this.h.style.cssText="display:inline-block;width:200%;height:200%;font-size:16px;max-width:none;";this.b.appendChild(this.h);this.c.appendChild(this.f);this.a.appendChild(this.b);this.a.appendChild(this.c)}
function t(a,b){a.a.style.cssText="max-width:none;min-width:20px;min-height:20px;display:inline-block;overflow:hidden;position:absolute;width:auto;margin:0;padding:0;top:-999px;white-space:nowrap;font-synthesis:none;font:"+b+";"}function z(a){var b=a.a.offsetWidth,c=b+100;a.f.style.width=c+"px";a.c.scrollLeft=c;a.b.scrollLeft=a.b.scrollWidth+100;return a.g!==b?(a.g=b,!0):!1}function A(a,b){function c(){var a=l;z(a)&&a.a.parentNode&&b(a.g)}var l=a;k(a.b,c);k(a.c,c);z(a)};function B(a,b){var c=b||{};this.family=a;this.style=c.style||"normal";this.weight=c.weight||"normal";this.stretch=c.stretch||"normal"}var C=null,D=null,F=null,G=null;function H(){if(null===D)if(K()&&/Apple/.test(window.navigator.vendor)){var a=/AppleWebKit\/([0-9]+)(?:\.([0-9]+))(?:\.([0-9]+))/.exec(window.navigator.userAgent);D=!!a&&603>parseInt(a[1],10)}else D=!1;return D}function K(){null===G&&(G=!!document.fonts);return G}
function L(){if(null===F){var a=document.createElement("div");try{a.style.font="condensed 100px sans-serif"}catch(b){}F=""!==a.style.font}return F}function M(a,b){return[a.style,a.weight,L()?a.stretch:"","100px",b].join(" ")}
B.prototype.load=function(a,b,c,l){var d=this,u=a||"BESbswy",v=0,E=b||3E3,I=(new Date).getTime();K()&&!H()?(a=new Promise(function(a,b){function c(){(new Date).getTime()-I>=E?b():document.fonts.load(M(d,'"'+d.family+'"'),u).then(function(b){1<=b.length?a():setTimeout(c,25)},function(){b()})}c()}),b=new Promise(function(a,b){v=setTimeout(b,E)}),Promise.race([b,a]).then(function(){clearTimeout(v);c(d)},function(){l(d)})):m(function(){function a(){var a;if(a=-1!=f&&-1!=g||-1!=f&&-1!=h||-1!=g&&-1!=h)(a=
f!=g&&f!=h&&g!=h)||(null===C&&(a=/AppleWebKit\/([0-9]+)(?:\.([0-9]+))/.exec(window.navigator.userAgent),C=!!a&&(536>parseInt(a[1],10)||536===parseInt(a[1],10)&&11>=parseInt(a[2],10))),a=C&&(f==w&&g==w&&h==w||f==x&&g==x&&h==x||f==y&&g==y&&h==y)),a=!a;a&&(e.parentNode&&e.parentNode.removeChild(e),clearTimeout(v),J||(c(d),J=!0))}function b(){if((new Date).getTime()-I>=E)e.parentNode&&e.parentNode.removeChild(e),l(d);else{var c=document.hidden;if(!0===c||void 0===c)f=n.a.offsetWidth,g=p.a.offsetWidth,
h=q.a.offsetWidth,a();v=setTimeout(b,50)}}var n=new r(u),p=new r(u),q=new r(u),f=-1,g=-1,h=-1,w=-1,x=-1,y=-1,e=document.createElement("div"),J=!1;e.dir="ltr";t(n,M(d,"sans-serif"));t(p,M(d,"serif"));t(q,M(d,"monospace"));e.appendChild(n.a);e.appendChild(p.a);e.appendChild(q.a);document.body.appendChild(e);w=n.a.offsetWidth;x=p.a.offsetWidth;y=q.a.offsetWidth;b();A(n,function(b){f=b;a()});t(n,M(d,'"'+d.family+'",sans-serif'));A(p,function(b){g=b;a()});t(p,M(d,'"'+d.family+'",serif'));A(q,function(b){h=
b;a()});t(q,M(d,'"'+d.family+'",monospace'))})};"object"===typeof module?module.exports=B:(window.FontFaceObserver=B,window.FontFaceObserver.prototype.load=B.prototype.load);}());
